# rustfmt configuration
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
reorder_imports = true

# Function formatting
fn_params_layout = "Tall"

# Misc formatting
newline_style = "Unix"
remove_nested_parens = true
use_small_heuristics = "Default"